LIB_SRC = Acceptor.cc  Channel.cc  EPoller.cc  EventLoop.cc  EventLoopThread.cc  InetAddress.cc  Socket.cc  SocketsOps.cc  Timer.cc  TimerQueue.cc TcpServer.cc TcpConnection.cc
BINARIES = test8

all: $(BINARIES)

include ../reactor.mk

test8: test8.cc
