LIB_SRC = Acceptor.cc  Channel.cc  EPoller.cc  EventLoop.cc  EventLoopThread.cc  InetAddress.cc  Socket.cc  SocketsOps.cc  Timer.cc  TimerQueue.cc TcpServer.cc TcpConnection.cc Buffer.cc Connector.cc
BINARIES = test11 test12

all: $(BINARIES)

include ../reactor.mk

test11: test11.cc
test12: test12.cc
