LIB_SRC = 			\
	Acceptor.cc		\
	Channel.cc		\
	EventLoop.cc		\
	EventLoopThread.cc	\
	InetAddress.cc		\
	Poller.cc		\
	Socket.cc		\
	SocketsOps.cc		\
	TcpConnection.cc	\
	TcpServer.cc		\
	Timer.cc		\
	TimerQueue.cc

#BINARIES = test1 test2 test3 test4 test5 test6 test7 test8
BINARIES = test8

all: $(BINARIES)

include ../reactor_lib.mk

test8: test8.cc
